[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.6"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/berto/excel-processor"
